application: your-app-id
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:

  #Manejador para las hojas de estilo
- url: /app
  static_dir: app



- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /rest/.*
  script: main.APP

- url: (.*)/
  #Define la pagina principal que se sirve
  static_files: app\1/index.html
  upload: app

- url: (.*)
  static_files: app\1
  upload: app
